name: EasterEggHunt
version: ${pom.version}

author: Schmoller

main: au.com.addstar.easteregghunt.HuntPlugin

depend: [Minigames,ProtocolLib]

permissions:
  easteregghunt.create:
    default: op

commands:
  eecreate:
    permission: easteregghunt.create
    usage: /<command> <name> 
  eeremove:
    permission: easteregghunt.create
    usage: /<command>
  eeremoveall:
    permission: easteregghunt.create
    usage: /<command> [radius]